#!/usr/bin/env bash

set -e -o pipefail
shopt -s globstar nullglob extglob

# not using .cargo/config because envvar set in there are ignored for the build
# and rustflags are ignored by cargo-fuzz because it sets envvars
export RUSTFLAGS="-C target-feature=+sse4.1"

task_bench() {
	echo 0 | sudo tee /sys/devices/system/cpu/cpufreq/boost &> /dev/null
	sudo cpupower frequency-set --governor performance &> /dev/null

	local user
	user="$(id -un)"

	# set scheudler to FIFO and pin to single CPU core
	sudo chrt -f 80 taskset -c 1 su "${user}" -c 'cargo bench'

	sudo cpupower frequency-set --governor powersave &> /dev/null
	echo 1 | sudo tee /sys/devices/system/cpu/cpufreq/boost &> /dev/null
}

task_fuzz() {
	cargo fuzz run parse_int --sanitizer none -- -max_total_time=1
}

main() {
	task="$1"
	shift

	set -o xtrace
	"task_${task}" "$@"
}

main "$@"
